services:
  coagente-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_EMAILJS_SERVICE_ID: service_op14y7a
        NEXT_PUBLIC_EMAILJS_TEMPLATE_ID: template_wmhhsin
        NEXT_PUBLIC_EMAILJS_PUBLIC_KEY: Evbsb35ak4Bwhndib
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_EMAILJS_SERVICE_ID=service_op14y7a
      - NEXT_PUBLIC_EMAILJS_TEMPLATE_ID=template_wmhhsin
      - NEXT_PUBLIC_EMAILJS_PUBLIC_KEY=Evbsb35ak4Bwhndib
    restart: unless-stopped 