# fly.toml app configuration file generated for coagente-webapp on 2025-06-02T17:30:02-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'coagente-webapp'
primary_region = 'lax'  # Los Angeles, CA - VERIFIED best latency (72ms vs 100ms QRO)

[build]

[env]
  NODE_ENV = "production"
  PORT = "3000"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

# Custom domains configuration
[[http_service.domains]]
  name = "coagente.com"

[[http_service.domains]]
  name = "www.coagente.com"

# Virtual machine configuration
[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

# Process configuration
[processes]
  app = "node server.js"

# Deploy configuration
[deploy]
  release_command = "echo 'Release command placeholder'"
  strategy = "rolling"
